name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sast_python_scan:
    name: SAST - Python Security Scan (Bandit)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan on Scraper
        run: bandit -r ./scraper -ll -i

  dast_zap_scan:
    name: DAST - OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    needs: sast_python_scan 
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'https://example.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
